// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package rpc_api

type Todo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	UserID string `json:"user_id"`
}
