"""
Python API client for Notify
"""
import re
import ast
from setuptools import setup, find_packages

_version_re = re.compile(r"__version__\s+=\s+(.*)")

with open("notifications_utils/version.py", "rb") as f:
    version = str(
        ast.literal_eval(_version_re.search(f.read().decode("utf-8")).group(1))
    )

setup(
    extras_require={
        "dev": [
            "apipkg==1.5",
            "appdirs==1.4.3",
            "atomicwrites==1.3.0",
            "attrs==19.3.0",
            "bandit==1.5.1",
            "black==19.10b0; python_version >= '3.6'",
            "bleach==3.1.4",
            "boto3==1.10.35",
            "botocore==1.13.35",
            "cached-property==1.5.1",
            "cerberus==1.3.2",
            "certifi==2019.11.28",
            "chardet==3.0.4",
            "click==7.1.1",
            "colorama==0.4.3",
            "coverage==5.0.4",
            "distlib==0.3.0",
            "docutils==0.15.2",
            "entrypoints==0.3",
            "execnet==1.7.1",
            "flake8==3.7.9",
            "flask==1.1.1",
            "flask-redis==0.4.0",
            "freezegun==0.3.10",
            "gitdb==4.0.2",
            "gitpython==3.1.0",
            "idna==2.8",
            "importlib-metadata==1.6.0; python_version < '3.8'",
            "itsdangerous==1.1.0",
            "jinja2==2.10.3",
            "jmespath==0.9.5",
            "markupsafe==1.1.1",
            "mccabe==0.6.1",
            "mistune==0.8.4",
            "monotonic==1.5",
            "more-itertools==8.2.0",
            "orderedmultidict==1.0.1",
            "orderedset==2.0.1",
            "packaging==19.2",
            "pathspec==0.7.0",
            "pbr==5.4.4",
            "pep517==0.8.1",
            "phonenumbers==8.11.0",
            "pip-shims==0.5.1",
            "pipenv-setup==3.0.1",
            "pipfile==0.0.2",
            "plette[validation]==0.2.3",
            "pluggy==0.7.1",
            "py==1.8.1",
            "pycodestyle==2.5.0",
            "pyflakes==2.1.1",
            "pyparsing==2.4.6",
            "pypdf2==1.26.0",
            "pytest==3.6.4",
            "pytest-cov==2.6.0",
            "pytest-forked==1.1.3",
            "pytest-mock==1.10.0",
            "pytest-xdist==1.22.2",
            "python-dateutil==2.8.0; python_version >= '2.7'",
            "python-json-logger==0.1.11",
            "pytz==2019.3",
            "pyyaml==5.2",
            "redis==3.3.11",
            "regex==2020.2.20",
            "requests==2.22.0",
            "requests-mock==1.4.0",
            "requirementslib==1.5.4",
            "s3transfer==0.2.1",
            "six==1.14.0",
            "smartypants==2.0.1",
            "smmap==3.0.1",
            "statsd==3.3.0",
            "stevedore==1.32.0",
            "toml==0.10.0",
            "tomlkit==0.5.11",
            "typed-ast==1.4.1",
            "typing==3.7.4.1",
            "urllib3==1.25.8; python_version >= '3.4'",
            "vistir==0.5.0",
            "webencodings==0.5.1",
            "werkzeug==1.0.0",
            "wheel==0.34.2",
            "zipp==3.1.0; python_version < '3.8'",
        ]
    },
    name="notifications-utils",
    version=version,
    url="https://github.com/alphagov/notifications-utils",
    license="MIT",
    author="Government Digital Service",
    description="Shared python code for Notify",
    long_description=__doc__,
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "bleach==3.1.4",
        "boto3==1.10.35",
        "botocore==1.13.35",
        "certifi==2019.11.28",
        "chardet==3.0.4",
        "click==7.1.1",
        "docutils==0.15.2",
        "flask==1.1.1",
        "flask-redis==0.4.0",
        "idna==2.8",
        "itsdangerous==1.1.0",
        "jinja2==2.10.3",
        "jmespath==0.9.5",
        "markupsafe==1.1.1",
        "mistune==0.8.4",
        "monotonic==1.5",
        "orderedset==2.0.1",
        "phonenumbers==8.11.0",
        "pypdf2==1.26.0",
        "python-dateutil==2.8.0; python_version >= '2.7'",
        "python-json-logger==0.1.11",
        "pytz==2019.3",
        "pyyaml==5.2",
        "redis==3.3.11",
        "requests==2.22.0",
        "s3transfer==0.2.1",
        "six==1.14.0",
        "smartypants==2.0.1",
        "statsd==3.3.0",
        "urllib3==1.25.8; python_version >= '3.4'",
        "webencodings==0.5.1",
        "werkzeug==1.0.0",
    ],
    setup_requires=["pytest-runner"],
    tests_require=[
        "pytest",
        "pytest-mock",
        "pytest-cov",
        "requests-mock",
        "freezegun",
        "flake8",
    ],
)
