#!/usr/bin/env bash

# Example usage for pushing services to y-cld:
# TARGET=y ./apply-services

set -euxo pipefail

: ${TARGET:="local"}

cfbin() {
  export CF_HOME="$HOME/.cf$TARGET"
  mkdir -p $CF_HOME
  cf $@
}

ROOT_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

cfbin target -o "dta" -s "notifications" || \
  cfbin login -sso -a "https://api.system.$TARGET.cld.gov.au"

for name in notify-shared notify-api notify-admin aws smtp telstra; do
  cfbin create-user-provided-service $name -p "$ROOT_PATH/ups/$name.json" || true
  cfbin update-user-provided-service $name -p "$ROOT_PATH/ups/$name.json"
done
