"""

Revision ID: 0216
Revises: 0215
Create Date: 2019-05-29 10:08:47.050835

"""
from alembic import op
import sqlalchemy as sa


revision = '0216'
down_revision = '0215'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_callback_type',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('name')
                    )
    op.execute("insert into service_callback_type values ('delivery_status'), ('complaint')")
    op.add_column('service_callback_api', sa.Column('callback_type', sa.String(), nullable=True))
    op.create_foreign_key("service_callback_api_type_fk", 'service_callback_api', 'service_callback_type', ['callback_type'], ['name'])
    op.add_column('service_callback_api_history', sa.Column('callback_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_callback_api_history', 'callback_type')
    op.drop_constraint("service_callback_api_type_fk", 'service_callback_api', type_='foreignkey')
    op.drop_column('service_callback_api', 'callback_type')
    op.drop_table('service_callback_type')
    # ### end Alembic commands ###
