"""

Revision ID: 0232
Revises: 0231
Create Date: 2019-07-12 18:47:26.633255

"""
from alembic import op
import sqlalchemy as sa


revision = '0232'
down_revision = '0231'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('archived', sa.Boolean(), nullable=True))
    op.execute('update jobs set archived = false')
    op.alter_column('jobs', 'archived', nullable=False, server_default=sa.false())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'archived')
    # ### end Alembic commands ###
