"""

Revision ID: 0233
Revises: 0232
Create Date: 2019-07-18 14:19:24.451953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '0233'
down_revision = '0232'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_folder',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('service_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['template_folder.id'], ),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_folder_map',
        sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('template_folder_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['template_folder_id'], ['template_folder.id'], ),
        sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
        sa.PrimaryKeyConstraint('template_id')
    )

    op.create_unique_constraint('ix_id_service_id', 'template_folder', ['id', 'service_id'])
    op.create_table('user_folder_permissions',
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('template_folder_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('service_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['template_folder_id', 'service_id'], ['template_folder.id', 'template_folder.service_id'], ),
        sa.ForeignKeyConstraint(['user_id', 'service_id'], ['user_to_service.user_id', 'user_to_service.service_id'], ),
        sa.ForeignKeyConstraint(['template_folder_id'], ['template_folder.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'template_folder_id', 'service_id'),
    )


def downgrade():
    op.drop_table('user_folder_permissions')
    op.drop_constraint('ix_id_service_id', 'template_folder', type_='unique')
    
    op.drop_table('template_folder_map')
    op.drop_table('template_folder')
    # ### end Alembic commands ###
