// Code generated by protoc-gen-go. DO NOT EDIT.
// source: defs/notify.proto

package notify

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_a8f52e06d363bc18, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_a8f52e06d363bc18, []int{1}
}
func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (dst *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(dst, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Permissions struct {
	Permissions          []string `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permissions) Reset()         { *m = Permissions{} }
func (m *Permissions) String() string { return proto.CompactTextString(m) }
func (*Permissions) ProtoMessage()    {}
func (*Permissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_a8f52e06d363bc18, []int{2}
}
func (m *Permissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permissions.Unmarshal(m, b)
}
func (m *Permissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permissions.Marshal(b, m, deterministic)
}
func (dst *Permissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permissions.Merge(dst, src)
}
func (m *Permissions) XXX_Size() int {
	return xxx_messageInfo_Permissions.Size(m)
}
func (m *Permissions) XXX_DiscardUnknown() {
	xxx_messageInfo_Permissions.DiscardUnknown(m)
}

var xxx_messageInfo_Permissions proto.InternalMessageInfo

func (m *Permissions) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type User struct {
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AuthType             string                  `protobuf:"bytes,2,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	EmailAddress         string                  `protobuf:"bytes,3,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	FailedLoginCount     int64                   `protobuf:"varint,4,opt,name=failed_login_count,json=failedLoginCount,proto3" json:"failed_login_count,omitempty"`
	PasswordChangedAt    string                  `protobuf:"bytes,5,opt,name=password_changed_at,json=passwordChangedAt,proto3" json:"password_changed_at,omitempty"`
	Permissions          map[string]*Permissions `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_a8f52e06d363bc18, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

func (m *User) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *User) GetFailedLoginCount() int64 {
	if m != nil {
		return m.FailedLoginCount
	}
	return 0
}

func (m *User) GetPasswordChangedAt() string {
	if m != nil {
		return m.PasswordChangedAt
	}
	return ""
}

func (m *User) GetPermissions() map[string]*Permissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Users)(nil), "Users")
	proto.RegisterType((*Permissions)(nil), "Permissions")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterMapType((map[string]*Permissions)(nil), "User.PermissionsEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotifyClient is the client API for Notify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotifyClient interface {
	GetUsers(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Users, error)
}

type notifyClient struct {
	cc *grpc.ClientConn
}

func NewNotifyClient(cc *grpc.ClientConn) NotifyClient {
	return &notifyClient{cc}
}

func (c *notifyClient) GetUsers(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/Notify/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServer is the server API for Notify service.
type NotifyServer interface {
	GetUsers(context.Context, *Request) (*Users, error)
}

func RegisterNotifyServer(s *grpc.Server, srv NotifyServer) {
	s.RegisterService(&_Notify_serviceDesc, srv)
}

func _Notify_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Notify/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).GetUsers(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Notify",
	HandlerType: (*NotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _Notify_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defs/notify.proto",
}

func init() { proto.RegisterFile("defs/notify.proto", fileDescriptor_notify_a8f52e06d363bc18) }

var fileDescriptor_notify_a8f52e06d363bc18 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0xd3, 0xa4, 0xed, 0xa4, 0x42, 0xbb, 0x82, 0x86, 0x16, 0x24, 0x44, 0x0f, 0x39,
	0x48, 0x0a, 0xf5, 0x52, 0xbc, 0x95, 0x22, 0x22, 0x14, 0x91, 0xa0, 0xe7, 0xb0, 0x76, 0xa7, 0x6d,
	0x30, 0x4d, 0x62, 0x66, 0xa3, 0xe4, 0xef, 0xf9, 0xcb, 0x64, 0x37, 0x15, 0x5b, 0x6f, 0x33, 0xdf,
	0x9b, 0x4c, 0x76, 0xde, 0x83, 0xa1, 0xc0, 0x35, 0x4d, 0xb2, 0x5c, 0x26, 0xeb, 0x3a, 0x2c, 0xca,
	0x5c, 0xe6, 0xbe, 0x0f, 0x9d, 0x08, 0x3f, 0x2a, 0x24, 0xc9, 0x2e, 0xa0, 0x53, 0x11, 0x96, 0x71,
	0x22, 0x5c, 0xc3, 0x33, 0x82, 0x5e, 0x64, 0xab, 0xf6, 0x51, 0xf8, 0xd7, 0x60, 0xbd, 0x12, 0x96,
	0xc4, 0xc6, 0x60, 0x29, 0x44, 0xae, 0xe1, 0x99, 0x81, 0x33, 0xb5, 0x42, 0x85, 0xa3, 0x86, 0xf9,
	0x13, 0x70, 0x9e, 0xb1, 0xdc, 0x25, 0x44, 0x49, 0x9e, 0x11, 0xf3, 0xc0, 0x29, 0xfe, 0x5a, 0xfd,
	0x45, 0x2f, 0x3a, 0x44, 0xfe, 0x77, 0x0b, 0xda, 0x6a, 0x01, 0x63, 0xd0, 0xce, 0xf8, 0x0e, 0xf7,
	0x7f, 0xd5, 0x35, 0x1b, 0x43, 0x8f, 0x57, 0x72, 0x1b, 0xcb, 0xba, 0x40, 0xb7, 0xa5, 0x85, 0xae,
	0x02, 0x2f, 0x75, 0x81, 0xec, 0x0a, 0x4e, 0x71, 0xc7, 0x93, 0x34, 0xe6, 0x42, 0x94, 0x48, 0xe4,
	0x9a, 0x7a, 0xa0, 0xaf, 0xe1, 0xbc, 0x61, 0xec, 0x06, 0xd8, 0x9a, 0x27, 0x29, 0x8a, 0x38, 0xcd,
	0x37, 0x49, 0x16, 0xaf, 0xf2, 0x2a, 0x93, 0x6e, 0xdb, 0x33, 0x02, 0x33, 0x1a, 0x34, 0xca, 0x52,
	0x09, 0x0b, 0xc5, 0x59, 0x08, 0x67, 0x05, 0x27, 0xfa, 0xca, 0x4b, 0x11, 0xaf, 0xb6, 0x3c, 0xdb,
	0xa0, 0x88, 0xb9, 0x74, 0x2d, 0xbd, 0x78, 0xf8, 0x2b, 0x2d, 0x1a, 0x65, 0x2e, 0xd9, 0xec, 0xf8,
	0x3c, 0x5b, 0x1b, 0x72, 0xae, 0x0d, 0x09, 0x0f, 0x6c, 0xb8, 0xcf, 0x64, 0x59, 0x1f, 0x9d, 0x3d,
	0x5a, 0xc2, 0xe0, 0xff, 0x00, 0x1b, 0x80, 0xf9, 0x8e, 0xf5, 0xde, 0x00, 0x55, 0x32, 0x1f, 0xac,
	0x4f, 0x9e, 0x56, 0xcd, 0xed, 0xce, 0xb4, 0x7f, 0xb8, 0x34, 0x6a, 0xa4, 0xbb, 0xd6, 0xcc, 0x98,
	0x06, 0x60, 0x3f, 0xe9, 0x3c, 0xd9, 0x25, 0x74, 0x1f, 0x50, 0x36, 0x41, 0x75, 0xc3, 0x7d, 0xa8,
	0x23, 0x5b, 0x3f, 0x89, 0xfc, 0x93, 0x37, 0x5b, 0x07, 0x7e, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x88, 0xec, 0xac, 0x46, 0x05, 0x02, 0x00, 0x00,
}
